main: me.fireballs.share.SharePlugin
version: 1.0.0
name: Share
description: "Share brady stats"
softdepend:
  - PGM
  - Core
commands:
  tbdebug:
    permission: tb.debug
  pe:
    permission: tb.effects
    aliases: [ persistenteffects ]
authors:
  - applepies